name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  schedule:
    - cron: "17 7 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install, build, and upload site
        uses: withastro/action@v6
        env:
          CALENDAR_ICS_URL: "https://calendar.google.com/calendar/ical/7b6d023ecb047c1e067a626369b8c967028b79ddc12bd34746765dc15e5c7506%40group.calendar.google.com/public/basic.ics"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
